models:
    build:  ./
    external_links:
      -  mysql:db
    volumes:
      - ./sugar:/app/sugar
    ports:
      - "8003:8000"
    command: bash -c "python /app/sugar/manage.py makemigrations && python /app/sugar/manage.py migrate && python /app/sugar/manage.py loaddata db.json && mod_wsgi-express start-server --working-directory /app/sugar --reload-on-changes /app/sugar/sugar/wsgi.py"

services:
   build: ./
   links:
      - models
   volumes:
      - ./services:/app/services
   ports:
      - "8002:8000"
   command: bash -c "pip install requests && mod_wsgi-express start-server --working-directory /app/services --reload-on-changes /app/services/services/wsgi.py"

web:
   build: ./
   links:
      - services
   volumes:
      - ./web:/app/web
   ports:
      - "8001:8000"
   command: bash -c "pip install requests && mod_wsgi-express start-server --url-alias /static /app/web/webapp/static --working-directory /app/web --reload-on-changes /app/web/web/wsgi.py"
