entities:
    build: ./
    container_name: sugar_entities
    external_links:
      -  mysql:db
    volumes:
      - ./entities:/app/entities
    ports:
      - "8003:8000"
    command: bash -c "python /app/entities/manage.py makemigrations && python /app/entities/manage.py migrate --noinput && python /app/entities/manage.py loaddata db.json && mod_wsgi-express start-server --working-directory /app/entities --reload-on-changes /app/entities/entities/wsgi.py"

services:
    build: ./
    container_name: sugar_services
    links:
       - entities
       - kafka
       - es
    volumes:
       - ./services:/app/services
    ports:
       - "8002:8000"
    command: bash -c "pip install requests && mod_wsgi-express start-server --working-directory /app/services --reload-on-changes /app/services/services/wsgi.py"

web:
    build: ./
    container_name: sugar_web
    links:
       - services
    volumes:
       - ./web:/app/web
    ports:
       - "8001:8000"
    command: bash -c "pip install requests && mod_wsgi-express start-server --url-alias /static /app/web/webapp/static --working-directory /app/web --reload-on-changes /app/web/web/wsgi.py"

kafka:
    image: spotify/kafka
    container_name: kafka
    environment:
       ADVERTISED_HOST: kafka
       ADVERTISED_PORT: 9092
    hostname: kafka

es:
    image: elasticsearch:2.0
    container_name: es
    ports:
       - "9200:9200"

batch:
    image: tp33/django
    container_name: batch
    links:
       - kafka:kafka
       - es:es
    volumes:
       - ./batch:/app/batch
    command: bash -c "python /app/batch/main.py"

selenium:
    image: tp33/django
    container_name: selenium
    links:
        - web
    ports:
        - "4444:4444"
    volumes:
       - ./selenium:/app/selenium
    command: bash -c "pip install selenium && python /app/selenium/main.py"